### PR TITLE
add link to fabric8/s2i-java

### PR DESCRIPTION
**Pull request by vorburger**
Hoi @tobru & Co. 

Würdet Ihr evtl. auf fabric8/s2i-java linken wollen? 

Nur ein höflicher Vorschlag! :smile: 

M.

### CODE REVIEW

**Comment by phil-pona** [comment]
Looks good to me, the fabric8/s2i-java stuff looks very promising, not only when it comes to s2i builds but also during runtime eg. catching dynamically Container Resource Limits.

I just recently switched to the fabric8/java-centos-openjdk8-jdk in one of our springboot examples: https://github.com/appuio/example-spring-boot-helloworld/blob/master/Dockerfile#L1

**Comment by vorburger** [comment]
@phil-pona thanks! So can you merge this? Or ping @tobru or other committers to merge this?

**Comment by vorburger** [comment]
@appuioorg

**Comment by vorburger** [comment]
FYI https://developers.redhat.com/blog/2018/12/18/openshift-java-s2i-builder-java-11-grade/

**Comment by tobru** [comment]
LGTM. Thanks.

**Pull request merged**
